### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by kevans91** [arduino/arduinoOTA#4]
Hello!

Sorry to be a pain, but can you clarify the licensing on this, please? =) The Arduino project is a nice hodgepodge of LGPL+GPL, so specificity here would be nice.

Thanks!

**Comment by facchinm** [comment]
Hi Kyle,
thanks for pointing this out! I just committed f9d50882798c3d4c4d75c22d84543d2ecc194ad4 adding the license file, thanks!

**Comment by kevans91** [comment]
Thanks!
