### ISSUE TITLE
How does one use this?

### ISSUE THREAD

**Issue by S2Doc** [arduino/arduinoOTA#6]
This is in the Arduino repository, but I do not see how it is to be used in the Arduino environment.  Can anyone offer some guidance?

**Comment by facchinm** [comment]
Hi @S2Doc ,
this tool works in conjunction with https://github.com/arduino-libraries/WiFi101OTA (and other OTA libraries as well).
Various commanline switches can be modified based on the firmware running on the other side, but the tool basically uploads a file to the microcontroller and then triggers some rest APIs to apply the update.

**Comment by S2Doc** [comment]
Thank you very much, @facchinm !   I'm going to have to study this a bit, but now I have a starting point.
